[package]
name = "rustooth"
version = "0.1.0"
edition = "2024"

[dependencies]
bluer = { version = "0.17.4", features = ["full"] }
tokio = { version = "1.48.0", features = ["full"] }
tokio-macros = "2.5.0"
